### PR TITLE
reader: tolerate strings without NULL terminator

### PR DESCRIPTION
**Pull request by jcolp**
At least one major manufacturer is producing strings in their FIT file without a NULL terminator.

This change makes it so that the entirety of the
contents of the data field can be used as the string, instead of assuming the last part will be a NULL
terminator.

### CODE REVIEW

**Comment by tormoder** [comment]
Would it be possible to add an example FIT file as testdata to show this behaviour?
For example in `testdata/misc`. And it may be as minimal as possible.

**Comment by jcolp** [comment]
Sure! I've added a FIT file which demonstrates this. Is there anything else you'd like?

**Comment by jcolp** [comment]
I can, though "go test -update" doesn't update things, is there another command I'm missing to do so?

**Comment by jcolp** [comment]
Ah, is it because I don't have Golden Cheetah data?

**Comment by tormoder** [comment]
Sorry, please use a `fingerprint` != 0 for the bootstrap entry, e.g. `1`,  and then run `go test -update`.

**Comment by jcolp** [comment]
That was successful, thanks!

**Comment by tormoder** [comment]
Thanks!

**Pull request merged**
